sudo: required
language: generic

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

git:
  depth: false

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: Test
      script:
        - docker-compose build
        - docker-compose run frontend npm run prettier:check
        - docker-compose run frontend npm run eslint
        - docker-compose run frontend npm run stylelint
        - docker-compose run frontend npm run build
        - docker-compose run backend bundle exec rubocop
        - docker-compose run backend bundle exec rake db:create
        - docker-compose run backend bin/rails db:migrate RAILS_ENV=development
        - docker-compose run backend bundle exec rspec

notifications:
  email: false
