language: ruby
sudo: false
cache: bundler

rbenv:
- 2.5.1

services:
- postgresql

addons:
  chrome: stable

install:
- bundle install --jobs=3 --retry=3 --without production

before_script:
- cp env.example .env
- psql -c 'create database kudos_backend_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- bundle exec rails db:migrate

script:
- bundle exec rspec

notifications:
  email: false
