version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: 
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
