version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: backend
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./frontend:/code
      - node_modules:/code/node_modules
    ports:
      - "9090:9090"
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
  node_modules:
