version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    restart: unless-stopped
    build: 
      context: backend
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./backend:/code
      - bundle:/bundle
      - docs:/docs
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  documentation:
    build:
      context: backend
      dockerfile: docker/docs/Dockerfile
    volumes:
      - docs:/usr/share/nginx/html
    ports:
      - "9000:80"
    depends_on:
      - backend

  frontend:
    build:
      context: frontend
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./frontend:/code
      - node_modules:/code/node_modules
    ports:
      - "9090:9090"
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
  node_modules:
  bundle:
  docs:
