# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "graphql", "~> 1.8", ">= 1.8.10"
gem "graphql-batch", "~> 0.3.10"

gem "httparty"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 5.2", ">= 5.2.1"
# Use postgresql as the database for Active Record
gem "pg", ">= 0.18", "< 2.0"
# Use Puma as the app server
gem "puma", "~> 3.0"
# Use SCSS for stylesheets
gem "sass-rails", "~> 5.0"
# Use Uglifier as compressor for JavaScript assets
gem "uglifier", ">= 1.3.0"
# Use react as the JavaScript library
gem "react-rails"
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem "turbolinks", "~> 5"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.5"
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
gem "bcrypt", "~> 3.1.7"
gem "json_web_token", "~> 0.3.5"
gem "settingslogic", "~> 2.0", ">= 2.0.9"

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem "database_cleaner", "~> 1.7"
  gem "dotenv-rails", "~> 2.5"
  gem "faker", "~> 1.9", ">= 1.9.1"
  gem "pry", "~> 0.11.3"
  gem "rubocop"
end

group :development do
  gem "graphql_playground-rails", "~> 2.0", ">= 2.0.1"
  gem 'graphlient', '~> 0.3.3'
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem "web-console", ">= 3.3.0"
  gem "listen", "~> 3.0.5"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "pry-rails"
end

group :test do
  gem "factory_bot_rails", "~> 4.8", ">= 4.8.2"
  gem "rspec-rails", "~> 3.8"
  gem "rspec-graphql_matchers", "~> 0.7.1"
  gem "shoulda-matchers", "~> 3.1", ">= 3.1.2"
  gem "simplecov", "~> 0.16.1", require: false
  gem "timecop", "~> 0.9.1"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
